### PR TITLE
Don't crash when profile has no name key

### LINKED ISSUE #120: Crash when contact has no "name" key
When running scli I get the following error:
```
{'uuid': 'b1332582-cd42-4237-b6c6-abc8f7047960', 'profileKey': 'k/88fevrviJRhb+NtKFctYJ8EFKUDTKv5J5arKhRank=', 'lastUpdateTimestamp': 0, 'profile': None}
Traceback (most recent call last):
  File "/usr/bin/scli", line 4324, in <module>
    main()
  File "/usr/bin/scli", line 4309, in main
    coord = Coordinate()
  File "/usr/bin/scli", line 3685, in __init__
    self._contacts = Contacts(sigdata)
  File "/usr/bin/scli", line 987, in __init__
    self.reload()
  File "/usr/bin/scli", line 990, in reload
    indivs_dicts, groups_dicts = self._sigdata.parse_data_file()
  File "/usr/bin/scli", line 877, in parse_data_file
    profile_names = self._get_profile_names()
  File "/usr/bin/scli", line 936, in _get_profile_names
    num = prof['name']
KeyError: 'name'
```
Printing the `prof` shows that it only has the following keys:
```
{'uuid': 'xxx', 'profileKey': 'xxx', 'lastUpdateTimestamp': 0, 'profile': None}
```
Maybe this line could just be moved to the `try`/`catch` block? See #121

### PR DESCRIPTION
**Pull request by AckslD**
closes #120

### CODE REVIEW

**Comment by exquo** [comment]
Thanks! Yes, given that the `name` field might be absent, moving that dict lookup into the `try/except` clause is the right thing here. 

I don't have any contacts that only have the `uuid` and not their phone numbers (that's what `profiles[i]['name']` are) in their profiles. Just out of curiosity, is there anything special about those contacts? 

Since there is no spec for what has to be in signal-cli's data file, I just go by what's in mine, and in some cases have to make assumptions about what "should" be expected to be there.

**Comment by AckslD** [comment]
@exquo Not completely sure actually, I'll try to find which contact that was and get back to you.

**Comment by AckslD** [comment]
Although, I'm not sure how to find that contact. I can see if in `~/.loca/share/signal-cli/data/<my-number>` but not in `signal-cli listContacts`

**Comment by exquo** [comment]
Sorry, I should have mentioned that: you can search for that `uuid` in other places in the signal-cli data file (`~/.loca/share/signal-cli/data/<my-number>`). The `uuid` corresponding to a contact is a field in both the `profileStore` and `contactStore`. So by searching for it you can find which contact that entry in `profileStore` corresponds to. 

By itself this of course will not tell you *why* that contact does not have a phone number in the `profileStore` like most (all?) of the rest normally do. But it might be a hint if you happen to know that the contact is "special" in some sense. Of course, there might not be anything apparently special about the contact; this might be caused by some signal configuration on your contact's side. In that case - oh well, it's just a bit of curiosity on my part anyway.

**Comment by AckslD** [comment]
No problem @exquo, thanks for the information!

So looking into this contact it seems to be someone who I haven't started a conversion with but we are both in the same group chat. I also don't have this contact in my contacts on my phone, not sure if that matters though.

**Comment by exquo** [comment]
That's a good clue, thanks!

**Pull request merged**
