### PR TITLE
Fixed :attach not accepting paths with spaces, and strikethrough formatting for ~~

### LINKED ISSUE #44: :attach fails to handle path with spaces
`:attach [path] [caption]` doesn't work if the path has contains spaces, even if the path is inside double quotes.

## To reproduce:
1. type `:attach "~/path with spaces dir/000.jpg"`

## Expected results:

* image is sent 

## Actual results:

* Shows the following error: `File does not exist: "~/path"`

## Details

Using `scli --debug`, in [`Commands.attach()`](https://github.com/isamert/scli/blob/dc8d6b660428002271e28a611fbb7829fd8bc225/scli#L556), the **actual behaviour** is 

```
args = ['"~/path', 'with', 'spaces', 'dir/000.jpg"']
```

The **expected behaviour** is

```
args = ['~/path with spaces dir/000.jpg']
```

Because args[0] = `"~/path`, python cannot find the path

Given `:a "~/path with spaces dir/000.jpg" caption with spaces`, the ideal fix would produce `args = ['~/path with spaces dir/000.jpg', 'caption', 'with', 'spaces']`

It seems like `args` is defined by string-splitting the text after `:`, with a space as the separator, in line [1075](https://github.com/isamert/scli/blob/dc8d6b660428002271e28a611fbb7829fd8bc225/scli#L1075)

### PR DESCRIPTION
**Pull request by yc-tsui**
Path with spaces should be enclosed with double quotes

Fixes #44

### CODE REVIEW

**Comment by isamert** [comment]
Can you send the fix for `:attach` separately so that I can merge it directly? Because I just realized that formatting also breaks when `**stuff**` or `__stuff__` appears in the text, a more generic solution is required here.

**Comment by yc-tsui** [comment]
Should I make a new branch on my fork, undo the changes for strikethrough formatting, and send that as a PR?

**Comment by isamert** [comment]
That's fine for me.

**Comment by yc-tsui** [comment]
Or ... I undo'ed the stuff for strikethrough on the master branch. This PR originally was opened to fix :attach anyway, so I can rename the PR and you can merge it.

**Comment by isamert** [comment]
Thanks!

**Pull request merged**
