### PR TITLE
Handle signal-cli's new accounts.json

### PR DESCRIPTION
**Pull request by mikeevmm**
This pull request seeks to solve https://github.com/isamert/scli/issues/182 .

I fudged the merges a little (I worked on master, then tried merging it to develop, then saw that develop was behind the upstream), sorry about that.

Also, **please see the TODOs** included; these are things I think the maintainer is in a better position to decide.

Finally, please test this PR with the old system, where the folder names match the numbers, to make sure I didn't break that; I don't have access to such a setup.

### CODE REVIEW

**Comment by exquo** [comment]
Thanks for the fix! I wrote one that is mostly the same as yours 70074a93c59eda1337b55fae0de0bd016a4bc0c2. If there are no issues, I can add it as another commit to this PR and merge the whole thing.

**Comment by mikeevmm** [comment]
Hi! Thanks, and yes; however I left a couple of comments for things that could help preserve backwards compatibility, I think.

**Comment by exquo** [comment]
Thanks for the comments! I've added replies on the commit page

**Comment by mikeevmm** [comment]
Sounds reasonable to me. Feel free to merge whenever you're ready to.

**Pull request merged**
