### PR TITLE
Implement Wayland clipboard support

### LINKED ISSUE #158: Support Wayland clipboard
Hello, thanks for this awesome app!

I am trying to get clipbard integration working, and having several issues.

I'm running on Wayland, so I have `clipboard-get-command = wl-paste -n` in my config. 

If the clipboard contains absolute path to a file, it works well 👍 

If clipboard contains raw image data of type `image/jpeg` it crashes:

<details>
<summary>Details...</summary>

```sh
$ wl-copy < Downloads/whackamole-900px.jpg

$ wl-paste -l
image/jpeg

$ scli (and paste with :c)
.....
  File "/usr/bin/scli", line 2935, in keypress
    return self._keypress_cmd_mode(key, key_orig, txt)
  File "/usr/bin/scli", line 2892, in _keypress_cmd_mode
    self._cmds.exec(cmd, *args)
  File "/usr/bin/scli", line 3965, in exec
    return fn(*args)
  File "/usr/bin/scli", line 4103, in attach_clip
    files = clip.files()
  File "/usr/bin/scli", line 450, in files
    return callf(cmd, capture_output=True).stdout.split('\n')
  File "/usr/bin/scli", line 102, in callf
    proc = subprocess.run(cmd, **subprocess_kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.10/subprocess.py", line 1149, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2038, in _communicate
    stdout = self._translate_newlines(stdout,
  File "/usr/lib/python3.10/subprocess.py", line 1026, in _translate_newlines
    data = data.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
</details>

If I copy an image from browser (right click - copy image), nothing happens.

Clipboard contents depend on a browser....

<details>
<summary>In Chromium:</summary>

```sh
$ wl-paste -l
text/x-moz-url
text/html
image/png

$ wl-paste -n
https://media.istockphoto.com/illustrations/mole-illustration-id1152565170?k=20&m=1152565170&s=612x612&w=0&h=INx4ZYSeEJBeT5-4pN_zRAoDnEDyU6pT-s9o94Xwuzo=
27 Whack A Mole Game Illustrations &amp; Clip Art - iStock
```
</details>

<details>
<summary>In qutebrowser (QtWebEngine):</summary>

```sh
$ wl-paste -l
application/x-qt-image
text/html
text/x-moz-url
image/png
image/bmp
image/cur
image/icns
image/ico
image/jp2
image/jpeg
image/jpg
image/pbm
image/pgm
image/ppm
image/tif
image/tiff
image/wbmp
image/webp
image/xbm
image/xpm

$ wl-paste -n
<img src="https://media.istockphoto.com/illustrations/game-to-hit-the-mole-illustration-id1153033854?k=20&amp;m=1153033854&amp;s=612x612&amp;w=0&amp;h=qJ-V8PXl9n8w5351vniVy1b9cLdqFHXMhxI5O2vQ44s=" alt="27 Whack A Mole Game Illustrations &amp;amp; Clip Art - iStock"/>
```
</details>

<details>
<summary>In Firefox:</summary>

```sh
$ wl-paste -l
text/html
text/_moz_htmlinfo
text/_moz_htmlcontext
image/png
image/bmp
image/x-bmp
image/x-MS-bmp
image/x-icon
image/x-ico
image/x-win-bitmap
image/vnd.microsoft.icon
application/ico
image/ico
image/icon
text/ico
image/jpeg
image/tiff
image/avif
SAVE_TARGETS

$ wl-paste -n
<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://media.istockphoto.com/illustrations/game-to-hit-the-mole-illustration-id1153033854?k=20&amp;m=1153033854&amp;s=612x612&amp;w=0&amp;h=qJ-V8PXl9n8w5351vniVy1b9cLdqFHXMhxI5O2vQ44s=" alt="27 Whack A Mole Illustrations &amp;amp; Clip Art - iStock" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb" data-noaft="1" style="width: 612px; height: 437px; margin: 0px;">
```

</details>

`--debug` shows that in all those cases `scli` tries to parse those as file paths:

```
DEBUG:root:callf: `['wl-paste', '-n']`
DEBUG:root:callf: <img src="https://media.istockphoto.com/illustrations/game-to-hit-the-mole-illustration-id1153033854?k=20&amp;m=1153033854&amp;s=612x612&amp;w=0&amp;h=qJ-V8PXl9n8w5351vniVy1b9cLdqFHXMhxI5O2vQ44s=" alt="27 Whack A Mole Game Illustrations &amp;amp; Clip Art - iStock"/>
WARNING:root:send_message: Attached file(s) does not exist.
DEBUG:root:callf: `['wl-paste', '-n']`
DEBUG:root:callf: <meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://media.istockphoto.com/illustrations/game-to-hit-the-mole-illustration-id1153033854?k=20&amp;m=1153033854&amp;s=612x612&amp;w=0&amp;h=qJ-V8PXl9n8w5351vniVy1b9cLdqFHXMhxI5O2vQ44s=" alt="27 Whack A Mole Illustrations &amp;amp; Clip Art - iStock" jsaction="load:XAeZkd;" jsname="HiaYvf" class="n3VNCb" data-noaft="1" style="width: 612px; height: 437px; margin: 0px;">
WARNING:root:send_message: Attached file(s) does not exist.
```

So it doesn't pick the right MIME-type from clipboard (obviously, as it just runs `wl-paste -n` as I told it to....)

For the last issue, do you think it's possible to teach `scli` to ask for the proper MIME type? On wayland, we can use `wl-paste -l` to list all available types, and select the type using `-t` like `wl-paste -t image/jpg`. Passing invalid type (jpg for a plaintext contents) will return an error. It works in Signal-Desktop, but they may be using some more native integration with clipboard. 

Thanks for your help!

### PR DESCRIPTION
**Pull request by maximbaz**
I finally got annoyed enough with absence of proper Wayland clipboard integration to get my hands on implementing this 😁 

This is almost a copy-paste of `xclip` support, with small refactoring to not duplicate actual logic.

No config required, and no behavior change should be done for existing users of `xclip` integration.

Fixes #158

### CODE REVIEW

**Comment by exquo** [comment]
Thanks for implementing the Wayland clipboard interaction! And sorry for a late reply!

> No config required, and no behavior change should be done for existing users of xclip integration.

👍 That's great!

Some comments on the code:

To reduce the code duplication, I think it's better to re-structure it a bit: make a base Clipboard class for most of the methods, and override a few attributes and methods in derived `Xclip` and `WLclip` classes. 

It's also preferable to test which clipboard manager is installed (with `use_xclip()`) only once, rather than every time the clipboard is used.

I've made a rough draft and pushed it in a commit here. Let me know what you think!

**Comment by maximbaz** [comment]
It's awesome, many thanks for the refactoring! 

I will get this tested, but from the first glance I have only one comment: with the current order of executables in `get_installed_clipb_manager`, wayland clipboard would be prioritized over X11 for people who happened to have both installed. If we do it this way, there is a potential that someone has both installed, and scli would suddenly behave differently for them. Don't know if it's purely theoretical risk, I just wanted to point this out 🙂

**Comment by maximbaz** [comment]
I fixed some small typos, and now it works as expected 👍

**Comment by exquo** [comment]
Yes, I will take another look at it soon! Sorry it had got delayed, appreciate your effort here!

**Comment by exquo** [comment]
Thanks for the reminder! Yes, it's time to pull this in. 

More of the clipboard related code needs to be rewritten. I've started on it in 56dfd25f95fc3752bb3ecb987f396d66a9fc2ff0, but have not completed it yet. However it's already an improvement on the current version, and can be used. 

I've added another commit with some more refactoring. If it works for Wayland, I can merge this PR into the main branch.

**Comment by maximbaz** [comment]
It still works as expected, thanks! During rebase, one of us must have pulled a few extra commits into this PR, which probably don't belong to it - could you confirm? Feel free to drop them if they are not necessary, or let me know and I can do it :+1: Otherwise, lets get this merged :raised_hands:

**Comment by exquo** [comment]
Thanks for testing!
The commits are from the `develop` branch. I have changed the merge-to branch to `develop`, and only the commits relevant to this PR show up.

**Comment by maximbaz** [comment]
Ahh, makes sense! Feel free to merge when you think it's ready, I have no more comments 😉

**Pull request closed without merging**
