### PR TITLE
Sort contacts fix

### PR DESCRIPTION
**Pull request by exquo**
A few improvements to displaying contacts.

### CODE REVIEW

**Comment by exquo** [comment]
With 7d71952ac3874219229acbe71188dbd0d7dd047e, the most-recent-message contacts sorting order is preserved between scli restarts only if `--save-history` is on. I think the users who don't save history want a "stateless" program, which looks the same after every restart. But let me know if you think the most-recent contacts order should be preserved regardless. A clean way to implement it would be to write a dummy history file with empty messages with timestamps in the right order.

**Comment by exquo** [comment]
For resolving merge conflict with #77, see 634f13bf15e889627cbc56b62bccd062b4f3fcb5.

**Comment by isamert** [comment]
Hi @exquo!
Thanks for the all the PRs. I have sent you an invite so that you can commit directly. I wanted to ask first but couldn't find your email, so I just sent it. If you have any other idea about the repo itself, or any other direction you want to take please feel free to contact me via email or just open a new issue.

One of the earlier PR's introduced a little bug related to the history but I merged them anyway. It seems to be a small thing, I'll handle it.

**Comment by exquo** [comment]
Awesome, thank you! I've just sent you an email reply. 

Sorry about the history issue! I've just pulled master and I see that after each time I restart scli every message in the history is doubled. That's due to `save_history()` registered twice `atexit`. This was part of the merge commit resolution in the comment above. Unfortunately, github view of it includes all the changes since master, rather then just the stuff relevant to the merge, so it's not very helpful. I will push the fix (now that I can :). Let me know if that's not the bug that you've meant.

**Pull request merged**
