### PR TITLE
Toggle reaction notifications, fix #176 #174

### LINKED ISSUE #176: Add option to disable notifications on receiving reactions
### Discussed in https://github.com/isamert/scli/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **maximbaz** February 15, 2022</sup>
I happen to receive lots of reactions in different chats, and it got me thinking about different ways we notify about them and whether it's useful...

First of all, in the bottom of `scli` we should information about a reaction, who did it and what was the reaction - I think it's useful, it's not distracting and it has some context 👍 

Then we count notifications in parenthesis in front of every chat - this I would say is not really useful, if I see `(23) Some Chat` and I open it and see no new messages, I'm a bit confused (I can infer that those 23 must have been reactions, but where they are I don't really know, nor do I probably care to track each one of them down 🙂 )

Finally we also have desktop notifications, which could be quite noisy, as reactions don't really require some _answer_ from me. 

It could be just my personal habits, that's why I thought to start from a discussion, to see what are your experiences.

Personally I'd not count reactions towards "unread counter" in front of every chat, nor would I send desktop notifications for them...</div>

### PR DESCRIPTION
**Pull request by cyrinux**
Hi here,

Please find present from @maximbaz and me to fix #176 and #174 .

Thanks for the project 😊

### CODE REVIEW

**Comment by exquo** [comment]
Thanks guys!

I've simplified the `send_desktop_notification()` usage. If we choose to not show notifications in the status line, all the changes can be reduced to a single line: 

```diff python
    def _on_receive_reaction(self, envelope):
         msg = self._add_reaction(envelope)
-        if is_envelope_outgoing(envelope):
+        if is_envelope_outgoing(envelope) or not cfg.notify_on_reactions:
         return
```
		
 On the one hand, not using `--notify-on-reactions` seems to imply no notifications of any kind - either desktop or in the status line. On the other hand, we currently apply all `notification..` options just to desktop notifications..

I've made some other minor changes - rewording, etc. Also, removed the line from readme, since that is just an example.

Let me know what you think!

**Comment by maximbaz** [comment]
Nice, thanks for the cleanup! Looks good to me. 

I think it does make sense to show notification in the status bar, it's not distracting, not confusing, and at the same time could be informative.

**Comment by cyrinux** [comment]
Cool, it make also sense for me, thanks @exquo .

**Comment by exquo** [comment]
Sounds good. Let's keep the status line notifications.
Thanks!

**Pull request merged**
