### PR TITLE
Misc improvments: style, efficiency

### PR DESCRIPTION
**Pull request by exquo**
This PR does not fix any bugs or introduce any new features, only improves the code quality in general.

### CODE REVIEW

**Comment by isamert** [comment]
Seems awesome!

**Comment by isamert** [comment]
Seems like 2d476ea causes auto-completion to use lowercase versions of the commands. This really disturbs the readability of the auto-complete list. I don't think command lookup really creates an overhead, even 100 command with multiple abbreviations will not take much time in the older implementation. I may simply revert this if can't find a better solution.

**Comment by isamert** [comment]
Following on earlier comment: I simply used the older data structure for completions, see 25f0d16.

**Comment by exquo** [comment]
Thanks!

Good call with the tab completion, it does look more readable with the capitalization.

I'm sure you're right about the performance - even on the slowest hardware the speed difference would probably not be noticeable. Still, I like the idea of conserving the CPU cycles :).

**Pull request merged**
